#Database
POSTGRES_SQL_USERNAME: postgres
POSTGRES_SQL_PASSWORD: postgres
POSTGRES_SQL_HOST: localhost
POSTGRES_SQL_PORT: 5432
POSTGRES_SQL_DB: crypto-alert-db

#Server
SERVER_PORT: 8080
ACTIVE_PROFILE: dev

#Email Config
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: alertcrypto28@gmail.com
EMAIL_PASSWORD: cfeqnnqmjkxmlakq
VERIFY_EMAIL_HOST: http://localhost:${SERVER_PORT}